entries:
- title: sidebar
  product: Meshing Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Utilities MMG Process
      url: /Kratos/pages/Applications/Meshing_Application/General/Utilities-MMG-Process.html
      output: web
    - title: Utilities ParMmg Process
      url: /Kratos/pages/Applications/Meshing_Application/General/Utilities-ParMmg-Process.html
      output: web
