entries:
- title: sidebar
  product: Particle Mechanics Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Particle_Mechanics_Application/General/Overview.html
      output: web
  - title: MPM example in GiD
    output: web
    folderitems:
    - title: Description
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/introduction.html
      output: web
    - title: Set up of example
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/set_up.html
      output: web
    - title: Meshing
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/meshing.html
      output: web
    - title: Description
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/calculation.html
      output: web
    - title: Post processing
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/post_processing.html
      output: web
    - title: Description
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/Description.html
      output: web
  - title: Examples
    output: web
    folderitems:
    - title: Granular flow 2d readme
      url: /pages/Applications/Particle_Mechanics_Application/Examples/remote_Granular_flow_2d_readme.html
      output: web
