entries:
- title: sidebar
  product: Shape Optimization Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Multi objective optimization
      url: /pages/Applications/Shape_Optimization_Application/General/Multi_objective_optimization.html
      output: web
    - title: Shape Optimization Application
      url: /pages/Applications/Shape_Optimization_Application/General/shape_optimization_application.html
      output: web
      subfolders:
      - title: Sensitivity Analysis
        output: web
        subfolderitems:
        - title: Adjoint approach
          url: /pages/Applications/Shape_Optimization_Application/General/Sensitivity_Analysis/Adjoint_approach.html
          output: web
        - title: Finite difference or direct approach
          url: /pages/Applications/Shape_Optimization_Application/General/Sensitivity_Analysis/Finite_difference_or_direct_approach.html
          output: web
  - title: Technologies
    output: web
    folderitems:
    - title: Vertex morphing
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Vertex_morphing.html
      output: web
    - title: Objectives and constraints
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Objectives_and_constraints.html
      output: web
      subfolders:
      - title: List of response functions
        output: web
        subfolderitems:
        - title: Angle of attack
          url: /pages/Applications/Shape_Optimization_Application/Technologies/List_of_response_functions/Angle_of_attack.html
          output: web
        - title: Face angle
          url: /pages/Applications/Shape_Optimization_Application/Technologies/List_of_response_functions/Face_angle.html
          output: web
        - title: Mesh based packaging
          url: /pages/Applications/Shape_Optimization_Application/Technologies/List_of_response_functions/Mesh_based_packaging.html
          output: web
        - title: Plane based packaging
          url: /pages/Applications/Shape_Optimization_Application/Technologies/List_of_response_functions/Plane_based_packaging.html
          output: web
        - title: Surface normal shape change
          url: /pages/Applications/Shape_Optimization_Application/Technologies/List_of_response_functions/Surface_normal_shape_change.html
          output: web
        - title: Total volume
          url: /pages/Applications/Shape_Optimization_Application/Technologies/List_of_response_functions/Total_volume.html
          output: web
  - title: Examples
    output: web
    folderitems:
    - title: Strain Energy Minimization 3D Shell
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Strain_Energy_Minimization_3D_Shell.html
      output: web
    - title: Bead Optimization Plate
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Bead_Optimization_Plate.html
      output: web
    - title: Multi Constraint Optimization 3D Hook
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Multi_Constraint_Optimization_3D_Hook.html
      output: web
    - title: Shape Update Optimization Stanford Bunny
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Shape_Update_Optimization_Stanford_Bunny.html
      output: web
