name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.md'
      - '/documents/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [Custom, FullDebug]
        compiler: [gcc, clang]
    steps:
    - run: 'echo "Documentation change. No build required" '

  windows:
    runs-on: windows-2022
    env:
      KRATOS_BUILD_TYPE: Custom

    steps:
    - run: 'echo "Documentation change. No build required" '
