name: Nightly Doxygen Build

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  doxygen_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Installing doxygen
        shell: bash
        run: sudo apt-get install doxygen graphviz -y
      - name: Build doxygen web page
        shell: bash
        run: cd documents && doxygen kratos_doxyfile

